import { prisma } from './prisma';
import { getAdminAlertRecipients, sendEmail } from './email';
import { sanitizeText } from './sanitize';
import { logError, logWarn } from './logger';

type EnquiryNotificationInput = {
  referenceCode: string;
  fullName: string;
  email: string;
  phone: string;
  subject: string;
  serviceInterest?: string | null;
  preferredContactMethod?: string | null;
  location?: string | null;
  message: string;
};

type QuoteNotificationInput = {
  referenceCode: string;
  fullName: string;
  email: string;
  phone: string;
  serviceType: string;
  projectType?: string | null;
  location?: string | null;
  estimatedBudgetRange?: string | null;
  preferredStartDate?: Date | null;
  siteVisitRequired: boolean;
  projectDescription: string;
};

type ReviewNotificationInput = {
  name: string;
  rating: number;
  projectContext?: string | null;
  message: string;
};

type ForumThreadNotificationInput = {
  title: string;
  slug: string;
  authorName: string;
  categoryName?: string | null;
};

type ForumReplyNotificationInput = {
  threadTitle: string;
  threadSlug: string;
  authorName: string;
};

function formatDate(value: Date | null | undefined) {
  if (!value) return 'Not specified';
  return value.toLocaleDateString('en-ZA', {
    year: 'numeric',
    month: 'short',
    day: '2-digit',
  });
}

function escapeHtml(input: string) {
  return input
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function buildShell(params: {
  title: string;
  intro: string;
  bodyHtml: string;
  signature?: string | null;
  footer?: string | null;
  companyName: string;
}) {
  const signature = params.signature || `Regards,<br />${escapeHtml(params.companyName)} Team`;
  const footer = params.footer || 'This message was generated by the Elchanan Construction business platform.';

  return `
    <div style="font-family:Arial,Helvetica,sans-serif;background:#050a15;padding:24px;color:#e4ecff;">
      <div style="max-width:680px;margin:0 auto;border:1px solid rgba(34,217,255,0.28);border-radius:20px;overflow:hidden;background:#0d1320;">
        <div style="padding:20px 24px;background:linear-gradient(135deg,#0a6fbd,#22d9ff);color:#021a2e;">
          <h1 style="margin:0;font-size:22px;line-height:1.2;">${escapeHtml(params.title)}</h1>
        </div>
        <div style="padding:24px;">
          <p style="margin:0 0 16px 0;color:#d2def8;">${escapeHtml(params.intro)}</p>
          ${params.bodyHtml}
          <p style="margin:20px 0 0 0;color:#d2def8;">${signature}</p>
        </div>
        <div style="padding:14px 24px;border-top:1px solid rgba(255,255,255,0.08);font-size:12px;color:#9ab0d3;">
          ${escapeHtml(footer)}
        </div>
      </div>
    </div>
  `;
}

async function getNotificationContext() {
  const [profile, adminUsers] = await Promise.all([
    prisma.companyProfile.findFirst({ orderBy: { createdAt: 'asc' } }).catch(() => null),
    prisma.adminUser.findMany({
      where: { isActive: true },
      select: { email: true },
      orderBy: { createdAt: 'asc' },
      take: 20,
    }).catch(() => []),
  ]);

  const configuredRecipients = getAdminAlertRecipients();
  const fallbackAdminRecipients = adminUsers.map((admin) => admin.email.toLowerCase());
  const adminRecipients = [...new Set([...
    configuredRecipients,
    ...fallbackAdminRecipients,
  ])].filter(Boolean);

  return {
    profile,
    adminRecipients,
    companyName: profile?.displayName || profile?.companyName || 'Elchanan Construction Company',
    companyEmail: profile?.email || 'hello@elchananconstruction.co.za',
  };
}

async function safeSend(message: {
  to: string | string[];
  subject: string;
  text: string;
  html: string;
  replyTo?: string;
}) {
  const result = await sendEmail(message);
  if (!result.ok) {
    logWarn('email.send_failed', {
      subject: message.subject,
      reason: result.error,
      provider: result.provider,
    });
  }
}

export async function sendEnquiryEmailNotifications(input: EnquiryNotificationInput) {
  try {
    const context = await getNotificationContext();

    if (context.adminRecipients.length) {
      const adminSubject = `[New Enquiry] ${input.referenceCode} - ${input.subject}`;
      const adminText = [
        `Reference: ${input.referenceCode}`,
        `Name: ${input.fullName}`,
        `Email: ${input.email}`,
        `Phone: ${input.phone}`,
        `Service: ${input.serviceInterest || 'General enquiry'}`,
        `Preferred contact: ${input.preferredContactMethod || 'Not specified'}`,
        `Location: ${input.location || 'Not specified'}`,
        `Message: ${input.message}`,
      ].join('\n');

      const adminHtml = buildShell({
        title: 'New Customer Enquiry',
        intro: 'A new customer enquiry has been submitted and requires review.',
        companyName: context.companyName,
        signature: context.profile?.emailSignature,
        footer: context.profile?.emailFooter,
        bodyHtml: `
          <p><strong>Reference:</strong> ${escapeHtml(input.referenceCode)}</p>
          <p><strong>Client:</strong> ${escapeHtml(input.fullName)} (${escapeHtml(input.email)})</p>
          <p><strong>Phone:</strong> ${escapeHtml(input.phone)}</p>
          <p><strong>Service:</strong> ${escapeHtml(input.serviceInterest || 'General enquiry')}</p>
          <p><strong>Preferred contact:</strong> ${escapeHtml(input.preferredContactMethod || 'Not specified')}</p>
          <p><strong>Location:</strong> ${escapeHtml(input.location || 'Not specified')}</p>
          <p><strong>Message:</strong><br/>${escapeHtml(input.message)}</p>
        `,
      });

      await safeSend({
        to: context.adminRecipients,
        subject: adminSubject,
        text: adminText,
        html: adminHtml,
        replyTo: input.email,
      });
    }

    const customerSubject = `We received your enquiry (${input.referenceCode})`;
    const customerText = [
      `Hello ${input.fullName},`,
      '',
      'Thank you for contacting Elchanan Construction Company.',
      `Your enquiry reference is ${input.referenceCode}.`,
      'Our team will review your message and follow up shortly with next steps.',
    ].join('\n');

    const customerHtml = buildShell({
      title: 'Enquiry Received',
      intro: `Thank you ${input.fullName}. We have received your enquiry.`,
      companyName: context.companyName,
      signature: context.profile?.emailSignature,
      footer: context.profile?.emailFooter,
      bodyHtml: `
        <p><strong>Reference:</strong> ${escapeHtml(input.referenceCode)}</p>
        <p><strong>Subject:</strong> ${escapeHtml(input.subject)}</p>
        <p><strong>Expected follow-up:</strong> Our team will contact you using your preferred channel.</p>
      `,
    });

    await safeSend({
      to: input.email,
      subject: customerSubject,
      text: customerText,
      html: customerHtml,
      replyTo: context.companyEmail,
    });
  } catch (error) {
    logError('notify.enquiry_failed', { error });
  }
}

export async function sendQuoteEmailNotifications(input: QuoteNotificationInput) {
  try {
    const context = await getNotificationContext();

    if (context.adminRecipients.length) {
      const adminSubject = `[New Quote Request] ${input.referenceCode} - ${input.serviceType}`;
      const adminText = [
        `Reference: ${input.referenceCode}`,
        `Name: ${input.fullName}`,
        `Email: ${input.email}`,
        `Phone: ${input.phone}`,
        `Service: ${input.serviceType}`,
        `Project type: ${input.projectType || 'Not specified'}`,
        `Budget: ${input.estimatedBudgetRange || 'Not specified'}`,
        `Start date: ${formatDate(input.preferredStartDate)}`,
        `Site visit required: ${input.siteVisitRequired ? 'Yes' : 'No'}`,
        `Project description: ${input.projectDescription}`,
      ].join('\n');

      const adminHtml = buildShell({
        title: 'New Quote Request',
        intro: 'A new quote request has been submitted and is awaiting estimator review.',
        companyName: context.companyName,
        signature: context.profile?.emailSignature,
        footer: context.profile?.emailFooter,
        bodyHtml: `
          <p><strong>Reference:</strong> ${escapeHtml(input.referenceCode)}</p>
          <p><strong>Client:</strong> ${escapeHtml(input.fullName)} (${escapeHtml(input.email)})</p>
          <p><strong>Phone:</strong> ${escapeHtml(input.phone)}</p>
          <p><strong>Service:</strong> ${escapeHtml(input.serviceType)}</p>
          <p><strong>Project type:</strong> ${escapeHtml(input.projectType || 'Not specified')}</p>
          <p><strong>Budget:</strong> ${escapeHtml(input.estimatedBudgetRange || 'Not specified')}</p>
          <p><strong>Preferred start:</strong> ${escapeHtml(formatDate(input.preferredStartDate))}</p>
          <p><strong>Site visit required:</strong> ${input.siteVisitRequired ? 'Yes' : 'No'}</p>
          <p><strong>Description:</strong><br/>${escapeHtml(input.projectDescription)}</p>
        `,
      });

      await safeSend({
        to: context.adminRecipients,
        subject: adminSubject,
        text: adminText,
        html: adminHtml,
        replyTo: input.email,
      });
    }

    const customerSubject = `Quote request received (${input.referenceCode})`;
    const customerText = [
      `Hello ${input.fullName},`,
      '',
      'Thank you for requesting a quote from Elchanan Construction Company.',
      `Your quote reference is ${input.referenceCode}.`,
      'Our estimator team will review your scope and follow up with practical next steps.',
    ].join('\n');

    const customerHtml = buildShell({
      title: 'Quote Request Received',
      intro: `Thank you ${input.fullName}. Your quote request is now in our review queue.`,
      companyName: context.companyName,
      signature: context.profile?.emailSignature,
      footer: context.profile?.emailFooter,
      bodyHtml: `
        <p><strong>Reference:</strong> ${escapeHtml(input.referenceCode)}</p>
        <p><strong>Service requested:</strong> ${escapeHtml(input.serviceType)}</p>
        <p><strong>Budget range:</strong> ${escapeHtml(input.estimatedBudgetRange || 'Not specified')}</p>
        <p><strong>Preferred start date:</strong> ${escapeHtml(formatDate(input.preferredStartDate))}</p>
      `,
    });

    await safeSend({
      to: input.email,
      subject: customerSubject,
      text: customerText,
      html: customerHtml,
      replyTo: context.companyEmail,
    });
  } catch (error) {
    logError('notify.quote_failed', { error });
  }
}

async function notifyAdmins(subject: string, lines: string[], htmlTitle: string) {
  const context = await getNotificationContext();
  if (!context.adminRecipients.length) return;

  const text = lines.join('\n');
  const html = buildShell({
    title: htmlTitle,
    intro: 'A new moderation item was submitted and may need review.',
    companyName: context.companyName,
    signature: context.profile?.emailSignature,
    footer: context.profile?.emailFooter,
    bodyHtml: `<pre style="white-space:pre-wrap;color:#d2def8;line-height:1.55;">${escapeHtml(text)}</pre>`,
  });

  await safeSend({
    to: context.adminRecipients,
    subject,
    text,
    html,
  });
}

export async function sendReviewAdminNotification(input: ReviewNotificationInput) {
  try {
    await notifyAdmins(
      '[New Review Submission] Pending moderation',
      [
        `Reviewer: ${sanitizeText(input.name, 160)}`,
        `Rating: ${input.rating}/5`,
        `Project context: ${sanitizeText(input.projectContext || 'Not specified', 220)}`,
        `Message: ${sanitizeText(input.message, 3000)}`,
      ],
      'New Review Submission',
    );
  } catch (error) {
    logError('notify.review_failed', { error });
  }
}

export async function sendForumThreadAdminNotification(input: ForumThreadNotificationInput) {
  try {
    await notifyAdmins(
      '[New Forum Thread] Pending moderation',
      [
        `Thread: ${sanitizeText(input.title, 220)}`,
        `Author: ${sanitizeText(input.authorName, 160)}`,
        `Category: ${sanitizeText(input.categoryName || 'General', 160)}`,
        `Thread URL slug: ${sanitizeText(input.slug, 220)}`,
      ],
      'New Forum Thread',
    );
  } catch (error) {
    logError('notify.forum_thread_failed', { error });
  }
}

export async function sendForumReplyAdminNotification(input: ForumReplyNotificationInput) {
  try {
    await notifyAdmins(
      '[New Forum Reply] Pending moderation',
      [
        `Thread: ${sanitizeText(input.threadTitle, 220)}`,
        `Reply author: ${sanitizeText(input.authorName, 160)}`,
        `Thread URL slug: ${sanitizeText(input.threadSlug, 220)}`,
      ],
      'New Forum Reply',
    );
  } catch (error) {
    logError('notify.forum_reply_failed', { error });
  }
}


